// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_middleware.ts";
import * as $2 from "./routes/auth/_middleware.ts";
import * as $3 from "./routes/auth/blog.tsx";
import * as $4 from "./routes/index.tsx";
import * as $5 from "./routes/login.tsx";
import * as $6 from "./routes/logout.tsx";
import * as $7 from "./routes/signUp.tsx";
import * as $$0 from "./islands/Button.tsx";
import * as $$1 from "./islands/Carousel.tsx";
import * as $$2 from "./islands/Counter.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_middleware.ts": $1,
    "./routes/auth/_middleware.ts": $2,
    "./routes/auth/blog.tsx": $3,
    "./routes/index.tsx": $4,
    "./routes/login.tsx": $5,
    "./routes/logout.tsx": $6,
    "./routes/signUp.tsx": $7,
  },
  islands: {
    "./islands/Button.tsx": $$0,
    "./islands/Carousel.tsx": $$1,
    "./islands/Counter.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
